name: fellow
description: A new Flutter extension project.
version: 0.0.1
homepage: https://github.com/ErselCakmak/fellow

environment:
  sdk: '>=2.18.0-44.1.beta <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:

